name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🐧 Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: v20.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: 🔍 Installation
        run: pnpm install
        working-directory: ./

      - name: 🔧 Build
        run: pnpm doc build
        working-directory: ./

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./documentation/dist
